POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "vptervon@elamshin.net",
    "password": "secret"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "matervon@edukai.net",
    "password": "secret"
}