POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZwdGVydm9uQGVsYW1zaGluLm5ldCIsIm5hbWUiOiJWUCBUZXJ2b25lbiIsImlkIjoxLCJpYXQiOjE2Njk5MDE4NDF9.pWKY6bGTjIVTL2mxtIiWq9_mfVxHc3GuwLYReuWptMU

{
    "author": "Greg Bear",
    "url": "www.gregbear.com",
    "title": "Blood Music"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZwdGVydm9uQGVsYW1zaGluLm5ldCIsIm5hbWUiOiJWUCBUZXJ2b25lbiIsImlkIjoxLCJpYXQiOjE2Njk5MDE4NDF9.pWKY6bGTjIVTL2mxtIiWq9_mfVxHc3GuwLYReuWptMU

{
    "author": "Peter Hamilton",
    "url": "www.phamilton.com",
    "title": "Naked God"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZwdGVydm9uQGVsYW1zaGluLm5ldCIsIm5hbWUiOiJWUCBUZXJ2b25lbiIsImlkIjoxLCJpYXQiOjE2Njk5MDE4NDF9.pWKY6bGTjIVTL2mxtIiWq9_mfVxHc3GuwLYReuWptMU

{
    "author": "Neil Simmons",
    "url": "www.carrioncomfort.com",
    "title": "Carrion Comfort"
}

###

GET http://localhost:3001/api/blogs

###

GET http://localhost:3001/api/blogs/1

###
DELETE http://localhost:3001/api/blogs/4
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZwdGVydm9uQGVsYW1zaGluLm5ldCIsIm5hbWUiOiJWUCBUZXJ2b25lbiIsImlkIjoxLCJpYXQiOjE2Njk5MDE4NDF9.pWKY6bGTjIVTL2mxtIiWq9_mfVxHc3GuwLYReuWptMU

###

PUT http://localhost:3001/api/blogs/6