POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZwdGVydm9uQGVsYW1zaGluLm5ldCIsIm5hbWUiOiJWUCBUZXJ2b25lbiIsImlkIjoxLCJpYXQiOjE2Njk5MjU1OTR9.YDFD5qx2pXqkOIwQ5GCWIN60iNr3Mt7mtMNUo5cMblM

{
    "author": "Greg Bear",
    "url": "www.gregbear.com",
    "title": "Blood Music"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZwdGVydm9uQGVsYW1zaGluLm5ldCIsIm5hbWUiOiJWUCBUZXJ2b25lbiIsImlkIjoxLCJpYXQiOjE2Njk5MjU1OTR9.YDFD5qx2pXqkOIwQ5GCWIN60iNr3Mt7mtMNUo5cMblM

{
    "author": "Peter Hamilton",
    "url": "www.phamilton.com",
    "title": "Naked God"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZwdGVydm9uQGVsYW1zaGluLm5ldCIsIm5hbWUiOiJWUCBUZXJ2b25lbiIsImlkIjoxLCJpYXQiOjE2Njk5MjU1OTR9.YDFD5qx2pXqkOIwQ5GCWIN60iNr3Mt7mtMNUo5cMblM

{
    "author": "Neil Simmons",
    "url": "www.carrioncomfort.com",
    "title": "Carrion Comfort"
}

###

GET http://localhost:3001/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZwdGVydm9uQGVsYW1zaGluLm5ldCIsIm5hbWUiOiJWUCBUZXJ2b25lbiIsImlkIjoxLCJpYXQiOjE2Njk5MjU1OTR9.YDFD5qx2pXqkOIwQ5GCWIN60iNr3Mt7mtMNUo5cMblM

###

GET http://localhost:3001/api/blogs?search=Carrion
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZwdGVydm9uQGVsYW1zaGluLm5ldCIsIm5hbWUiOiJWUCBUZXJ2b25lbiIsImlkIjoxLCJpYXQiOjE2Njk5MjU1OTR9.YDFD5qx2pXqkOIwQ5GCWIN60iNr3Mt7mtMNUo5cMblM

###

GET http://localhost:3001/api/blogs/1

###
DELETE http://localhost:3001/api/blogs/7
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZwdGVydm9uQGVsYW1zaGluLm5ldCIsIm5hbWUiOiJWUCBUZXJ2b25lbiIsImlkIjoxLCJpYXQiOjE2Njk5MjU1OTR9.YDFD5qx2pXqkOIwQ5GCWIN60iNr3Mt7mtMNUo5cMblM

###

PUT http://localhost:3001/api/blogs/6